//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeReference) DeepCopyInto(out *NodeReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeReference.
func (in *NodeReference) DeepCopy() *NodeReference {
	if in == nil {
		return nil
	}
	out := new(NodeReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeNodeInProgress) DeepCopyInto(out *UpgradeNodeInProgress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeNodeInProgress.
func (in *UpgradeNodeInProgress) DeepCopy() *UpgradeNodeInProgress {
	if in == nil {
		return nil
	}
	out := new(UpgradeNodeInProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeNodeInProgress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeNodeInProgressList) DeepCopyInto(out *UpgradeNodeInProgressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeNodeInProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeNodeInProgressList.
func (in *UpgradeNodeInProgressList) DeepCopy() *UpgradeNodeInProgressList {
	if in == nil {
		return nil
	}
	out := new(UpgradeNodeInProgressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeNodeInProgressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeNodeInProgressSpec) DeepCopyInto(out *UpgradeNodeInProgressSpec) {
	*out = *in
	out.NodeRef = in.NodeRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeNodeInProgressSpec.
func (in *UpgradeNodeInProgressSpec) DeepCopy() *UpgradeNodeInProgressSpec {
	if in == nil {
		return nil
	}
	out := new(UpgradeNodeInProgressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeOperationInProgress) DeepCopyInto(out *UpgradeOperationInProgress) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeOperationInProgress.
func (in *UpgradeOperationInProgress) DeepCopy() *UpgradeOperationInProgress {
	if in == nil {
		return nil
	}
	out := new(UpgradeOperationInProgress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeOperationInProgress) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeOperationInProgressList) DeepCopyInto(out *UpgradeOperationInProgressList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpgradeOperationInProgress, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeOperationInProgressList.
func (in *UpgradeOperationInProgressList) DeepCopy() *UpgradeOperationInProgressList {
	if in == nil {
		return nil
	}
	out := new(UpgradeOperationInProgressList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpgradeOperationInProgressList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
