apiVersion: upgrade.aks.io/v1alpha1
kind: UpgradeOperation
metadata:
  name: mixed-upgrade
  annotations:
    kubernetes.azure.com/upgradeOperationId: "d2ec2e13-2d6f-4f16-b42e-d6d3f2228a2c"
    kubernetes.azure.com/targetKubernetesVersion: "1.33.5"
spec:
  - type: Cluster
    targetNames:
    - my-aks-cluster
  - type: NodePool
    targetNames:
    - systempool
    - userpool
